import type { Metadata } from "next";
import "./globals.css";
import { quickSand } from "@/fonts";
import Footer from "@/components/shared/Footer";
import ContactUs from "@/components/contactus/contactUs";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${quickSand.className}  antialiased`}>
        {children}
        <ContactUs />
        <Footer />
      </body>
    </html>
  );
}
